#!/usr/bin/bash

#echo 'enter file path to structure'
#read fpath
#echo 'enter path to comparison cluster folder'
#read cc
#echo 'enter path to list of comparison structures'
#read list
#echo 'enter output file id'
#read id

echo "which cluster to do the inter for all of its structures?"
read i

base=/mnt/c/Users/boop/Sync/vernal-project/cifs/instance_cifs/
structure_list=${base}/${i}_dir_/ins_list_$i
listothers=${base}/3658to3679-/inter_list_$i

while read p; 
do
	id = inter_${p::-4}
  	$(RNAalign ${base}/3658to3679-/${p} -dir2 ${base}/3658to3679- ${listothers} -outfmt 2 > ${base}/3658to3679-/Results/${id})
done < $structure_list